# Generated by Django 3.1.8 on 2021-04-26 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.IntegerField(
                        blank=True, editable=False, unique=True
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount", models.IntegerField()),
                (
                    "active",
                    models.BooleanField(
                        choices=[(True, "Active"), (False, "Not Active")],
                        default=False,
                    ),
                ),
                (
                    "set_expiry",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")],
                        default=False,
                    ),
                ),
                (
                    "set_quantity",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")],
                        default=False,
                    ),
                ),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
