# Generated by Django 3.1.8 on 2021-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_auto_20210429_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
