# Generated by Django 3.1.8 on 2021-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210419_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="friendly_name",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
