# Generated by Django 3.1.8 on 2021-04-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210420_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.product'),
            preserve_default=False,
        ),
    ]
