# Generated by Django 3.1.8 on 2021-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20210422_1203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="products.Category"),
        ),
    ]
