# Generated by Django 3.1.8 on 2021-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210423_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Not Active')], default=True),
        ),
    ]
